"""FFmpeg 结构体字段偏移（**自动生成，别手改**）。

生成方式：``python3 tools/生成偏移.py``（用 C 编译器的 offsetof 打印，
见该脚本里的说明：FFmpeg 结构体里夹着私有字段，手写会随版本错位）。

本次生成：145 个字段。运行期只按偏移读，不需要编译器。

⚠️ 结构体布局**随 FFmpeg 大版本变化**：这份表只对下面这个主版本有效。
   绑定层会在启动时用 avcodec_version() 核对，不匹配就直接报错，
   绝不会拿错位的偏移去读内存（Windows CI 上正是这么抓到 61/63 混用的）。
"""

from __future__ import annotations

#: 这份偏移表对应的 libavcodec 主版本
对应主版本 = '63'

__all__ = ["偏移", "大小", "偏移表", "对应主版本"]

#: 结构体.字段 → 字节偏移
偏移: dict[str, int] = {
    'AVChannelLayout.nb_channels': 4,
    'AVChannelLayout.opaque': 16,
    'AVChannelLayout.order': 0,
    'AVChannelLayout.u': 8,
    'AVChapter.end': 24,
    'AVChapter.id': 0,
    'AVChapter.metadata': 32,
    'AVChapter.start': 16,
    'AVChapter.time_base': 8,
    'AVCodec.capabilities': 24,
    'AVCodec.id': 20,
    'AVCodec.long_name': 8,
    'AVCodec.name': 0,
    'AVCodec.type': 16,
    'AVCodecContext.bit_rate': 56,
    'AVCodecContext.ch_layout': 352,
    'AVCodecContext.codec_id': 24,
    'AVCodecContext.codec_type': 12,
    'AVCodecContext.err_recognition': 528,
    'AVCodecContext.extradata': 72,
    'AVCodecContext.extradata_size': 80,
    'AVCodecContext.flags': 64,
    'AVCodecContext.flags2': 68,
    'AVCodecContext.frame_size': 376,
    'AVCodecContext.get_format': 192,
    'AVCodecContext.height': 116,
    'AVCodecContext.hw_device_ctx': 560,
    'AVCodecContext.level': 692,
    'AVCodecContext.lowres': 720,
    'AVCodecContext.pix_fmt': 136,
    'AVCodecContext.pkt_timebase': 92,
    'AVCodecContext.profile': 688,
    'AVCodecContext.sample_rate': 344,
    'AVCodecContext.skip_frame': 704,
    'AVCodecContext.skip_idct': 700,
    'AVCodecContext.skip_loop_filter': 696,
    'AVCodecContext.thread_count': 656,
    'AVCodecContext.thread_type': 660,
    'AVCodecContext.time_base': 84,
    'AVCodecContext.width': 112,
    'AVCodecParameters.bit_rate': 48,
    'AVCodecParameters.bits_per_coded_sample': 56,
    'AVCodecParameters.bits_per_raw_sample': 60,
    'AVCodecParameters.ch_layout': 128,
    'AVCodecParameters.codec_id': 4,
    'AVCodecParameters.codec_tag': 8,
    'AVCodecParameters.codec_type': 0,
    'AVCodecParameters.extradata': 16,
    'AVCodecParameters.extradata_size': 24,
    'AVCodecParameters.format': 44,
    'AVCodecParameters.frame_size': 160,
    'AVCodecParameters.height': 76,
    'AVCodecParameters.level': 68,
    'AVCodecParameters.profile': 64,
    'AVCodecParameters.sample_rate': 152,
    'AVCodecParameters.video_delay': 120,
    'AVCodecParameters.width': 72,
    'AVDictionaryEntry.key': 0,
    'AVDictionaryEntry.value': 8,
    'AVFormatContext.bit_rate': 112,
    'AVFormatContext.chapters': 80,
    'AVFormatContext.duration': 104,
    'AVFormatContext.flags': 128,
    'AVFormatContext.iformat': 8,
    'AVFormatContext.interrupt_callback': 216,
    'AVFormatContext.max_delay': 124,
    'AVFormatContext.metadata': 192,
    'AVFormatContext.nb_chapters': 72,
    'AVFormatContext.nb_streams': 44,
    'AVFormatContext.pb': 32,
    'AVFormatContext.start_time': 96,
    'AVFormatContext.streams': 48,
    'AVFrame.best_effort_timestamp': 304,
    'AVFrame.buf': 184,
    'AVFrame.chroma_location': 296,
    'AVFrame.color_primaries': 284,
    'AVFrame.color_range': 280,
    'AVFrame.color_trc': 288,
    'AVFrame.colorspace': 292,
    'AVFrame.crop_bottom': 352,
    'AVFrame.crop_left': 360,
    'AVFrame.crop_right': 368,
    'AVFrame.crop_top': 344,
    'AVFrame.data': 0,
    'AVFrame.decode_error_flags': 320,
    'AVFrame.duration': 408,
    'AVFrame.extended_buf': 248,
    'AVFrame.extended_data': 96,
    'AVFrame.flags': 276,
    'AVFrame.format': 116,
    'AVFrame.height': 108,
    'AVFrame.hw_frames_ctx': 328,
    'AVFrame.linesize': 64,
    'AVFrame.metadata': 312,
    'AVFrame.nb_extended_buf': 256,
    'AVFrame.nb_samples': 112,
    'AVFrame.nb_side_data': 272,
    'AVFrame.opaque': 168,
    'AVFrame.opaque_ref': 336,
    'AVFrame.pict_type': 120,
    'AVFrame.pkt_dts': 144,
    'AVFrame.pts': 136,
    'AVFrame.quality': 160,
    'AVFrame.repeat_pict': 176,
    'AVFrame.sample_aspect_ratio': 124,
    'AVFrame.sample_rate': 180,
    'AVFrame.side_data': 264,
    'AVFrame.time_base': 152,
    'AVFrame.width': 104,
    'AVInputFormat.extensions': 24,
    'AVInputFormat.flags': 16,
    'AVInputFormat.long_name': 8,
    'AVInputFormat.name': 0,
    'AVPacket.buf': 0,
    'AVPacket.data': 24,
    'AVPacket.dts': 16,
    'AVPacket.duration': 64,
    'AVPacket.flags': 40,
    'AVPacket.opaque': 80,
    'AVPacket.opaque_ref': 88,
    'AVPacket.pos': 72,
    'AVPacket.pts': 8,
    'AVPacket.side_data': 48,
    'AVPacket.side_data_elems': 56,
    'AVPacket.size': 32,
    'AVPacket.stream_index': 36,
    'AVPacket.time_base': 96,
    'AVRational.den': 4,
    'AVRational.num': 0,
    'AVStream.avg_frame_rate': 88,
    'AVStream.codecpar': 16,
    'AVStream.disposition': 64,
    'AVStream.duration': 48,
    'AVStream.id': 12,
    'AVStream.index': 8,
    'AVStream.metadata': 80,
    'AVStream.nb_frames': 56,
    'AVStream.r_frame_rate': 204,
    'AVStream.start_time': 40,
    'AVStream.time_base': 32,
}

#: 各结构体的 sizeof（校验用：和 C 侧对不上就说明 ABI 变了）
大小: dict[str, int] = {
    'AVCodecParameters': 184,
    'AVFormatContext': 480,
    'AVFrame': 424,
    'AVPacket': 104,
    'AVStream': 216,
}


def 偏移表(结构: str, 字段: str) -> int:
    """取偏移；没有这个字段时抛 KeyError（比悄悄读错内存好）。"""
    return 偏移[f"{结构}.{字段}"]

